- name: Install mongodb
  hosts: all
  become: true
  tasks:
    - name: Add key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
    - name: Add repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present
    - name: Start mongodb
      systemd:
        name: mongod
        enabled: yes
